// GENERATED by scripts/sync-modules.mjs — do not edit.
// The source is src/utils/moduleCatalogue.json; run `node scripts/sync-modules.mjs` after
// changing it. The union exists so a mistyped module key is a compile error
// instead of a key that quietly matches nothing.
export type ModuleKey =
  | 'Synagogues'
  | 'PrayerTimes'
  | 'Zmanim'
  | 'Businesses'
  | 'Mikveh'
  | 'Events'
  | 'Eruv'
  | 'Gemach'
  | 'Selichot'
  | 'mikvehBooking'
  | 'zmanimSettings';
