// GENERATED by scripts/sync-catalogue.mjs — do not edit.
// The source is src/utils/roleCatalogue.json; run `node scripts/sync-catalogue.mjs` after
// changing it.
// ORDER IS PRIORITY, highest authority first. computePrimaryRole walks it to
// collapse a role set down to the single `role` field the rules read, so
// reordering an entry changes which role an account reports as its primary.
export type UserRole =
  | 'super_admin'
  | 'dev'
  | 'city_admin'
  | 'content_admin'
  | 'event_manager'
  | 'kosher_manager'
  | 'mikveh_manager'
  | 'eruv_manager'
  | 'business_manager'
  | 'gabbai'
  | 'user';
