/**
 * Publishes the module catalogue, so nothing has to keep a second copy of it.
 *
 *   node scripts/sync-modules.mjs [--check]
 *
 * src/utils/moduleCatalogue.json is the one place a module is declared. From it
 * this writes two things:
 *
 *   src/utils/moduleKeys.ts   the ModuleKey union, so a typo in the app is a
 *                             compile error rather than a key that silently
 *                             matches nothing. Generated, and committed.
 *   config/modules            the same list in Firestore, which the admin
 *                             console renders its switches from. The console
 *                             keeps no list of its own, so it cannot drift.
 *
 * Why not let Firestore be the source outright: a module is not a name, it is a
 * screen. Adding "בית עלמין" to a document does not create one, so only the
 * app's own source can say what exists. This makes the console learn that list
 * instead of restating it.
 *
 * --check verifies the generated file is current without writing or publishing,
 * for running before a build.
 */
import { initializeApp, cert } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import { readFileSync, writeFileSync } from 'fs';

const CHECK = process.argv.includes('--check');
const CATALOGUE = 'src/utils/moduleCatalogue.json';
const KEYS_FILE = 'src/utils/moduleKeys.ts';

const catalogue = JSON.parse(readFileSync(CATALOGUE, 'utf8'));
if (!Array.isArray(catalogue) || !catalogue.length) {
  console.error(`${CATALOGUE} is empty or not an array — refusing to publish.`);
  process.exit(1);
}
for (const m of catalogue) {
  if (!m.key || !m.label || !m.kind) {
    console.error(`entry missing key/label/kind: ${JSON.stringify(m)}`);
    process.exit(1);
  }
  if (m.kind !== 'section' && m.kind !== 'feature') {
    console.error(`${m.key}: kind must be "section" or "feature"`);
    process.exit(1);
  }
}

const generated = `// GENERATED by scripts/sync-modules.mjs — do not edit.
// The source is ${CATALOGUE}; run \`node scripts/sync-modules.mjs\` after
// changing it. The union exists so a mistyped module key is a compile error
// instead of a key that quietly matches nothing.
export type ModuleKey =
${catalogue.map((m) => `  | '${m.key}'`).join('\n')};
`;

const current = (() => {
  try { return readFileSync(KEYS_FILE, 'utf8'); } catch { return null; }
})();

if (CHECK) {
  if (current?.replace(/\r\n/g, '\n') !== generated) {
    console.error(`${KEYS_FILE} is out of date — run: node scripts/sync-modules.mjs`);
    process.exit(1);
  }
  console.log(`${KEYS_FILE} is current (${catalogue.length} modules).`);
  process.exit(0);
}

writeFileSync(KEYS_FILE, generated);
console.log(`wrote ${KEYS_FILE} (${catalogue.length} modules)`);

initializeApp({ credential: cert(JSON.parse(readFileSync('scripts/serviceAccount.json', 'utf8'))) });
await getFirestore().collection('config').doc('modules').set({
  modules: catalogue,
  updatedAt: new Date().toISOString(),
});
console.log('published to config/modules — the console picks it up on its next load');
